# Generated by Django 2.1 on 2018-10-30 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactoemergencia',
            old_name='contacto_emergencia',
            new_name='usuario',
        ),
    ]
